"""initial

Revision ID: 075703a2057d
Revises: 
Create Date: 2026-07-12 22:35:07.479906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '075703a2057d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarot_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_zh', sa.String(length=32), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('arcana', sa.String(length=16), nullable=False),
    sa.Column('suit', sa.String(length=16), nullable=True),
    sa.Column('element', sa.String(length=8), nullable=True),
    sa.Column('image_description', sa.Text(), nullable=False),
    sa.Column('keywords_upright', sa.Text(), nullable=False),
    sa.Column('keywords_reversed', sa.Text(), nullable=False),
    sa.Column('meaning_upright', sa.Text(), nullable=False),
    sa.Column('meaning_reversed', sa.Text(), nullable=False),
    sa.Column('love_upright', sa.Text(), nullable=False),
    sa.Column('love_reversed', sa.Text(), nullable=False),
    sa.Column('career_upright', sa.Text(), nullable=False),
    sa.Column('career_reversed', sa.Text(), nullable=False),
    sa.Column('finance_upright', sa.Text(), nullable=False),
    sa.Column('finance_reversed', sa.Text(), nullable=False),
    sa.Column('health_upright', sa.Text(), nullable=False),
    sa.Column('health_reversed', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarot_cards_name_zh'), 'tarot_cards', ['name_zh'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('openid', sa.String(length=128), nullable=False),
    sa.Column('unionid', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=False),
    sa.Column('member_expires_at', sa.DateTime(), nullable=True),
    sa.Column('free_readings_today', sa.Integer(), nullable=False),
    sa.Column('free_chats_today', sa.Integer(), nullable=False),
    sa.Column('paid_readings_balance', sa.Integer(), nullable=False),
    sa.Column('last_reading_date', sa.DateTime(), nullable=True),
    sa.Column('annual_report_data', sa.Text(), nullable=True),
    sa.Column('annual_report_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('diary_entries',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('mood', sa.String(length=16), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['tarot_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_entries_user_id'), 'diary_entries', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('readings',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('spread_type', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=16), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_user_id'), 'readings', ['user_id'], unique=False)
    op.create_table('share_logs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('sharer_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True, comment='wechat_friend / wechat_moments / qq / link / image / other'),
    sa.Column('share_type', sa.String(length=32), nullable=True, comment='reading / card / diary / mini_program'),
    sa.Column('ref_id', sa.String(length=64), nullable=True, comment='optional reference — reading_id / card_id etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sharer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_logs_sharer_id'), 'share_logs', ['sharer_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reading_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawn_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reading_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(length=32), nullable=False),
    sa.Column('is_reversed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['tarot_cards.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drawn_cards')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_share_logs_sharer_id'), table_name='share_logs')
    op.drop_table('share_logs')
    op.drop_index(op.f('ix_readings_user_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_diary_entries_user_id'), table_name='diary_entries')
    op.drop_table('diary_entries')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tarot_cards_name_zh'), table_name='tarot_cards')
    op.drop_table('tarot_cards')
    # ### end Alembic commands ###
