"""add journal_streak_reward_week

Revision ID: 22bb33cc44dd
Revises: 94e0ea795d95
Create Date: 2026-08-11 09:42:03.113609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '22bb33cc44dd'
down_revision: Union[str, None] = '94e0ea795d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 手工核对：只保留 users 表 journal_streak_reward_week 一列
    # （连续 7 天记录星尘奖励的 ISO 周幂等键，VARCHAR(8)，如 "2026-W33"）。
    # autogenerate 顺带报出的 horoscope_history VARCHAR→CHAR / 外键漂移与本任务
    # 无关，属既有 drift（与 96dab641fe3d 注释同源），不在本迁移中处理。
    op.add_column('users', sa.Column('journal_streak_reward_week', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'journal_streak_reward_week')
    # ### end Alembic commands ###
