"""add stardust fields

Revision ID: 96dab641fe3d
Revises: a5f6b7c8d9e0
Create Date: 2026-08-10 22:58:13.871518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '96dab641fe3d'
down_revision: Union[str, None] = 'a5f6b7c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 手工核对：只保留 users 表两列（stardust_total / star_tier）。
    # autogenerate 顺带报出的 horoscope_history VARCHAR→CHAR / 外键漂移与本任务无关，
    # 属既有 drift（由 SQLite 方言差异与历史手改模型引起），不在本迁移中处理。
    op.add_column('users', sa.Column('stardust_total', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('star_tier', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'star_tier')
    op.drop_column('users', 'stardust_total')
    # ### end Alembic commands ###
