"""allow null star_tier

Revision ID: d4e5f6a7b8c9
Revises: c2d3e4f5a6b7c8d9
Create Date: 2026-08-11 09:20:00.000000

最终审查 F-5：users.star_tier 允许 NULL（NULL 表示未推导，读取处由
tier_for(stardust_total) 兜底——share.py card-info 的 `is not None` 分支
因此成为可测的真实状态；tasks.py 等读取处均用 `or 0` 防御）。
SQLite 不支持 ALTER COLUMN，用 batch_alter_table 重建表实现。
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd4e5f6a7b8c9'
down_revision: Union[str, None] = 'c2d3e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'star_tier',
            existing_type=sa.Integer(),
            server_default='0',
            existing_server_default='0',
            nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 回退前把 NULL 星阶归一为 0（NOT NULL 重建表不允许 NULL 行）
    op.execute("UPDATE users SET star_tier = 0 WHERE star_tier IS NULL")
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'star_tier',
            existing_type=sa.Integer(),
            server_default='0',
            existing_server_default='0',
            nullable=False,
        )
    # ### end Alembic commands ###
