"""add_checkins_and_teaching_tables

Revision ID: d527f8eddb43
Revises: 26b711eeb4c1
Create Date: 2026-07-26 22:47:59.335462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd527f8eddb43'
down_revision: Union[str, None] = '26b711eeb4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_teaching',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('symbols', sa.Text(), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('keywords_learning', sa.Text(), nullable=False),
    sa.Column('life_connection', sa.Text(), nullable=False),
    sa.Column('element_association', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['tarot_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    op.create_table('checkins',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'checkin_date', name='uq_user_checkin_date')
    )
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('community_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['tarot_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_topics_date'), 'community_topics', ['date'], unique=True)
    op.create_table('invites',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('inviter_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('invitee_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('reward_granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitee_id')
    )
    op.create_index(op.f('ix_invites_inviter_id'), 'invites', ['inviter_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['community_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_topic_id'), 'community_posts', ['topic_id'], unique=False)
    op.add_column('users', sa.Column('invite_code', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('share_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('free_deep_readings', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('reward_tier', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.drop_column('users', 'reward_tier')
    op.drop_column('users', 'free_deep_readings')
    op.drop_column('users', 'share_count')
    op.drop_column('users', 'invite_code')
    op.drop_index(op.f('ix_community_posts_topic_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_invites_inviter_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_community_topics_date'), table_name='community_topics')
    op.drop_table('community_topics')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_table('card_teaching')
    # ### end Alembic commands ###
