"""initial: all models

Revision ID: e3baa4f8e221
Revises: 
Create Date: 2026-07-12 00:11:56.959907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3baa4f8e221'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('annual_report_data', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('annual_report_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'annual_report_year')
    op.drop_column('users', 'annual_report_data')
    # ### end Alembic commands ###
